// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuyFile() {
  return window['go']['main']['App']['BuyFile']();
}

export function GetFilesForSale() {
  return window['go']['main']['App']['GetFilesForSale']();
}

export function GetMyName() {
  return window['go']['main']['App']['GetMyName']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UploadFile() {
  return window['go']['main']['App']['UploadFile']();
}
