// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuyFile():Promise<void>;

export function GetFilesForSale():Promise<Array<main.RegisteredFile>>;

export function GetMyName():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function UploadFile():Promise<main.FileInfo>;
